services:
  api-fm:
    build: 
      context: .
      dockerfile: Dockerfile
    image: file-manager-app-img  # Built once and used for replicas
    deploy:
      replicas: 4
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - filedata:/file-manager
    env_file:
      - .env
    command: "php-fpm"
    networks:
      - fm-network
    depends_on:
      - db-fm
      - redis-fm

  webserver-fm:
    image: nginx:alpine
    container_name: webserver-fm
    restart: unless-stopped
    ports:
      - "${WEBSERVER_PORT:-8080}:80"
    env_file:
      - .env
    volumes:
      - .:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
      - filedata:/file-manager
    networks:
      - fm-network
    depends_on:
      - api-fm

  db-fm:
    image: mysql:8.0
    container_name: db-fm
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - fm-network

  redis-fm:
    image: redis:alpine
    container_name: redis-fm
    restart: unless-stopped
    networks:
      - fm-network
  
  horizon-fm:
    image: file-manager-app-img
    container_name: horizon-fm
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - filedata:/file-manager
    command: php artisan horizon
    networks:
      - fm-network
    depends_on:
      - api-fm
      - redis-fm
  
  reverb-fm:
    image: file-manager-app-img
    container_name: reverb-fm
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - filedata:/file-manager
    env_file:
      - .env
    command: php artisan reverb:start --debug
    networks:
      - fm-network
    depends_on:
      - api-fm

volumes:
  dbdata:
  filedata:

networks:
  fm-network:
    driver: bridge