apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-fm
  namespace: file-manager
  labels:
    app: redis-fm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-fm
  template:
    metadata:
      labels:
        app: redis-fm
    spec:
      containers:
      - name: redis
        image: redis:alpine
        ports:
        - containerPort: 6379
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"