apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-fm
  namespace: file-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-fm
  template:
    metadata:
      labels:
        app: api-fm
    spec:
      containers:
        - name: api-fm
          image: molero3111/file_manager:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9000 # PHP-FPM listens on port 9000
          envFrom:
            - configMapRef:
                name: file-manager-config
            - secretRef:
                name: file-manager-secret
          volumeMounts:
            - name: file-storage
              mountPath: /file-manager
      volumes:
        - name: file-storage
          emptyDir: {}
