apiVersion: v1
kind: Service
metadata:
  name: api-fm
  namespace: file-manager
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 8080 # Expose the app on port 8080 of the host machine
  selector:
    app: api-fm
