events {}

http {
    upstream backend {
        least_conn;  # Send traffic to the least busy container
        server api-fm:9000 max_fails=3 fail_timeout=30s;
    }

    client_max_body_size 20G; # Allow uploads up to 20GB
    client_body_timeout 3600s; # Increase timeout for large uploads

    server {
        listen 80;
        server_name localhost;
        root /var/www/html/public;
        index index.php index.html index.htm;

        location / {
            try_files $uri $uri/ /index.php?$query_string;
        }

        location ~ \.php$ {
            include fastcgi_params;
            fastcgi_pass backend;  # Use the upstream backend
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }

        location ~ /\.ht {
            deny all;
        }

        location /reverb {
            proxy_pass http://reverb-fm:8083;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_set_header Host $host;
            proxy_read_timeout 60s;
        }
    }
}

